app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='app'
urlpatterns = [
    path('', views.index, name='index'),
    path('subject_detail/<int:subject_pk>/', views.subject_detail, name="subject_detail"),
    path('comment_add/<int:subject_pk>/', views.comment_add, name="comment_add"),
    path('edit/<int:comment_pk>/', views.edit, name="edit"),
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name="app/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('like/<int:subject_pk>/<int:like_pk>/<str:do>/', views.push_like, name="push_like"),
]

lecinfo_share/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('test_share/', include('test_share.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_share/urls.py
from django.urls import path
from . import  views

app_name="test_share"
urlpatterns = [
    path('', views.index, name="index"),
    path('subject_detail/<int:subject_pk>/', views.subject_detail, name="subject_detail"),
    path('test_add/<int:subject_pk>/', views.test_add, name="test_add"),
    path('like/<int:subject_pk>/<int:like_pk>/<str:do>/', views.push_like, name="push_like"),
]

test_share/models.py
from django.db import models
from app.models import Subject, Like
from django.utils import timezone

class Test_Image(models.Model):
    YEAR_CHOICES = []
    for y in range(timezone.now().year, timezone.now().year - 10 , -1):
        YEAR_CHOICES.append((y, y))
    TITLE_CHOICES = [
        ('中間テスト', '中間テスト'),
        ('期末テスト', '期末テスト'),
        ('レポート', 'レポート'),
        ('小テスト', '小テスト'),
        ('授業資料', '授業資料'),
        ('その他', 'その他'),
    ]
    image = models.ImageField(upload_to='test_image')
    user = models.ForeignKey('users.User', on_delete=models.PROTECT)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    year = models.IntegerField(verbose_name="テスト実施年度", choices=YEAR_CHOICES, default=timezone.now().year)
    title = models.CharField(choices=TITLE_CHOICES, max_length=50, default='中間テスト')
    comment = models.TextField(verbose_name="テストへのコメント", blank=True, null=True)
    like = models.OneToOneField(Like, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

test_share/forms.py
from django.forms import ModelForm
from django import forms
from .models import Test_Image

class TestImageForm(ModelForm):
    class Meta:
        model = Test_Image
        fields = ['title', 'year', 'image', 'comment']

test_share/views.py
from django.shortcuts import render, redirect, get_object_or_404
from app.models import Subject, Like
from django.contrib.auth.decorators import login_required
from .forms import TestImageForm
from django.contrib.auth import login, authenticate
from app.forms import CustomUserCreationForm

def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            input_email = form.cleaned_data['email']
            input_password = form.cleaned_data['password1']
            input_username = form.cleaned_data['username']
            new_user = authenticate(email=input_email, password=input_password)
            if new_user is not None:
                login(request, new_user)
                return redirect('test_share:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'test_share/signup.html', {'form': form})


def index(request):
    subjects = Subject.objects.order_by('college').order_by('school')
    return render(request, 'test_share/index.html', {'subjects': subjects})

def subject_detail(request, subject_pk):
    subject = Subject.objects.get(pk=subject_pk)
    test_images = subject.test_image_set.all().order_by('-like__num')
    done = False
    test_image_pk = -1
    for test_image in test_images:
        if request.user == test_image.user:
            done = True
            test_image_pk = test_image.pk
    context = {
        'subject': subject,
        'test_images': test_images,
        'done': done,
        'test_images_pk': test_image_pk,
    }
    return render(request, 'test_share/subject_detail.html', context)






@login_required
def test_add(request, subject_pk):
    subject = Subject.objects.get(pk=subject_pk)
    if request.method == "POST":
        form = TestImageForm(request.POST, request.FILES)
        if form.is_valid():
            test_image = form.save(commit=False)
            test_image.user = request.user
            test_image.subject = subject
            test_image.like = Like.objects.create()
            test_image.save()
        return redirect('test_share:subject_detail', subject_pk=subject_pk)
    else:
        form = TestImageForm()
    return  render(request, 'test_share/test_add.html', {'form': form, 'subject_pk': subject_pk})


@login_required
def push_like(request, subject_pk, like_pk, do):
    like = get_object_or_404(Like, pk=like_pk)
    if request.method == "POST":
        if do == "like":
            like.user.add(request.user)
            like.num += 1
            like.save()
        else:
            like.user.remove(request.user)
            like.num -= 1
            like.save()
    return redirect('test_share:subject_detail', subject_pk=subject_pk)

test_share/templates/test_share/base.html
{% load static %}

<html>
 <head>
     <title>過去問共有サイト</title>
     <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
     <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
     <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
 </head>

 <body>
 <header>
     <div class="container">
         <a href="{% url 'test_share:index' %}"><h1>過去問共有サイト</h1></a>
         <div class="head-menu">
             {% if request.user.is_authenticated %}
                 <a href="{% url 'app:logout' %}">ログアウト</a>
                 <p>{{ user.username }}さん、過去問を共有しましょう！</p>
             {% else %}
                 <a href="{% url 'app:login' %}">ログイン</a>
                 <a href="{% url 'app:signup' %}">新規登録</a>
             {% endif %}
             <a href="{% url 'app:index' %}">講義情報共有サイトはこちら</a>
         </div>
     </div>
 </header>

 <div class="container">
     {% block content %}{% endblock %}
 </div>

 </body>
</html>

test_share/templates/test_share/index.html
{% extends 'test_share/base.html' %}

{% block content %}

<div class="iberalarts">
<h3>一般教養科目</h3>
{% for subject in subjects %}
　　 {% if subject.college is None %}
         <ul>
         {{ subject.name }}
         <a href="{% url 'test_share:subject_detail' subject_pk=subject.pk %}">
             過去問を閲覧する
         </a>
         </ul>
    {% endif %}
{% endfor %}
</div>
<div class="specialized">
<h3>専門科目</h3>
{% for subject in subjects %}
    {% if subject.college is not None %}
        <ul>
            {{ subject.college }} {{ subject.school }}の{{ subject.name }}
            <a href="{% url 'test_share:subject_detail' subject_pk=subject.pk %}">
                過去問を閲覧する
            </a>
        </ul>
    {% endif %}
{% endfor %}
</div>
{% endblock %}

test_share/templates/test_share/subject_detail.html
{% extends 'test_share/base.html' %}

{% block content %}

<header>
    <a href="{% url 'test_share:test_add' subject_pk=subject.pk %}">過去問・レポート課題・授業資料を投稿する</a>
</header>

{% if subject.college is not None %}
<h3>専門科目</h3>
<p>{{ subject.college }}  |  {{ subject.school }}</p>
{% else %}
<h3>一般教養科目</h3>
{% endif %}
<p>科目:{{ subject.name }}</p>
<p>担当教官:{{ subject.professor }}</p>

{% if test_images.count != 0 %}
    {% for test_image in test_images %}
        {{ test_image.title }} | {{ test_image.year }}
        <br>
        <img src="{{ test_image.image.url }}" class="test_image">
        <br>
        {{ test_image.comment }}
        {{ test_image.like.num }}いいね
        {% if request.user.is_authenticated %}
            {% if request.user not in test_image.like.user.all %}
                <form action="{% url 'test_share:push_like' subject_pk=test_image.subject.pk like_pk=test_image.like.pk do='like' %}" method="post">{% csrf_token %}
                        <button type="submit" value="{{ test_add.pk }}"><i class="fas fa-lg fa-heart like-red">いいねする</i></button>
                </form>
            {% else %}
                <form action="{% url 'test_share:push_like' subject_pk=test_image.subject.pk like_pk=test_image.like.pk do='unlike' %}" method="post">{% csrf_token %}
                    <button type="submit" value="{{ test_add.pk }}"><i class="fas fa-lg fa-heart">いいねをやめる</i></button>
                </form>
            {% endif %}
        {% endif %}
        <br>
    {% endfor %}
{% endif %}

{% endblock %}

test_share/templates/test_share/test_add.html
{% extends 'test_share/base.html' %}

{% block content %}

<div>
    <a href="{% url 'test_share:index' %}">ホームへ戻る</a>
</div>

<form action="{% url 'test_share:test_add' subject_pk=subject_pk%}" method="post" enctype="multipart/form-data">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit" class="btn">共有する</button>
</form>
{% endblock %}