app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='app'
urlpatterns = [
    path('', views.index, name='index'),
    path('subject_detail/<int:subject_pk>/', views.subject_detail, name="subject_detail"),
    path('comment_add/<int:subject_pk>/', views.comment_add, name="comment_add"),
    path('edit/<int:comment_pk>/', views.edit, name="edit"),
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name="app/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('like/<int:subject_pk>/<int:like_pk>/<str:do>/', views.push_like, name="push_like"),
]

lecinfo_share/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('test_share/', include('test_share.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_share/urls.py
from django.urls import path
from . import  views

app_name="test_share"
urlpatterns = [
    path('', views.index, name="index"),
    path('subject_detail/<int:subject_pk>/', views.subject_detail, name="subject_detail"),
    path('test_add/<int:subject_pk>/', views.test_add, name="test_add"),
    path('like/<int:subject_pk>/<int:like_pk>/<str:do>/', views.push_like, name="push_like"),
]

app/models.py
from django.db import models


class Subject(models.Model):
    name = models.CharField(max_length=50)
    professor = models.CharField(max_length=50)
    college = models.CharField(max_length=20, blank=True, null=True)
    school = models.CharField(max_length=20, blank=True, null=True)
    cource = models.CharField(max_length=20, blank=True, null=True)
    def __str__(self):
        return self.name

class Like(models.Model):
    user = models.ManyToManyField('users.User',  blank=True)
    num = models.IntegerField(default=0)
    liked_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    text = models.TextField(verbose_name="講義の感想・評価")
    user = models.ForeignKey('users.User', on_delete=models.PROTECT)
    like = models.OneToOneField(Like, on_delete=models.CASCADE, default=False)
    created_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.user.username

app/templates/app/base.html
{% load static %}

<html>
 <head>
     <title>講義情報共有サイト</title>
     <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
     <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
     <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
 </head>

 <body>
 <header>
     <div class="container">
         <a href="{% url 'app:index' %}"><h1>講義情報共有サイト</h1></a>
         <div class="head-menu">
             {% if request.user.is_authenticated %}
                 <a href="{% url 'app:logout' %}">ログアウト</a>
                 <p>{{ user.username }}さん、講義情報を共有しましょう！</p>
             {% else %}
                 <a href="{% url 'app:login' %}">ログイン</a>
                 <a href="{% url 'app:signup' %}">新規登録</a>
             {% endif %}
             <a href="{% url 'test_share:index' %}">過去問共有サイトはこちら</a>
         </div>
     </div>
 </header>

 <div class="container">
     {% block content %}{% endblock %}
 </div>

 </body>
</html>

app/templates/app/comment_add.html
{% extends 'app/base.html' %}

{% block content %}
<div>
    <a href="{% url 'app:index' %}">ホームに戻る</a>
</div>
<form action="{% url 'app:comment_add' subject_pk=subject.pk %}" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn">投稿する</button>
</form>

{% endblock %}

app/templates/app/edit.html
{% extends 'app/base.html' %}

{% block content %}
    <h1>コメント編集</h1>
    <form action="{% url 'app:edit' comment_pk=comment.pk %}" method="post">{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button class="btn" type="submit">保存する</button>
    </form>
    <a href="{% url 'app:subject_detail' subject_pk=comment.subject.pk %}">
        講義情報画面へ戻る
    </a>
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}

<div class="iberalarts">
<h3>一般教養科目</h3>
{% for subject in subjects %}
　　 {% if subject.college is None %}
         <ul>
         {{ subject.name }}
         ({{ subject.comment_set.all.count }}個のコメントが寄せられています。)
         <a href="{% url 'app:subject_detail' subject_pk=subject.pk %}">
             閲覧
         </a>
         </ul>
    {% endif %}
{% endfor %}
</div>
<div class="specialized">
<h3>専門科目</h3>
{% for subject in subjects %}
    {% if subject.college is not None %}
        <ul>
            {{ subject.college }} {{ subject.school }}の{{ subject.name }}
            ({{ subject.comment_set.all.count }}個のコメントが寄せられています。)
            <a href="{% url 'app:subject_detail' subject_pk=subject.pk %}">
                コメントを閲覧する
            </a>
        </ul>
    {% endif %}
{% endfor %}
</div>
{% endblock %}

app/templates/app/like.html
{{ comments

app/templates/app/login.html
{% extends 'app/base.html' %}

{% block content %}

<form class="form-signin" method="post">{% csrf_token %}
    {% if form.errors %}
        <p>ユーザー名かパスワードが間違っています</p>
    {% endif %}
    <h2>ログイン</h2>
    <label>メールアドレス</label>
    <input name="username">
    <br>
    <label>パスワード</label>
    <input name="password">
    <br>
    <input type="submit" name="ログイン">
</form>

{% endblock %}

app/templates/app/signup.html
{% extends 'app/base.html' %}

{% block content %}

<h2>ユーザー登録</h2>

<form method="post" action="{% url 'app:signup' %}">{% csrf_token %}
    <label>ユーザー名</label>
    {{ form.username }}
    {{ form.username.errors }}
    <br>
    <label>メールアドレス</label>
    {{ form.email }}
    {{ form.email.errors }}
    <br>
    <label>パスワード</label>
    {{ form.password1 }}
    {{ form.password1.errors }}
    <br>
    <label>パスワード(確認用)</label>
    {{ form.password2 }}
    {{ form.password2.error }}
    <br>
    <input type="submit" name="新規登録">
</form>

{% endblock %}

app/templates/app/subject_detail.html
{% extends 'app/base.html' %}


{% block content %}
{% load dict_tag %}
<header>
{% if done %}
<a href="{% url 'app:edit' comment_pk=comment_pk %}">コメントを編集する</a>
{% else %}
<a href="{% url 'app:comment_add' subject_pk=subject.pk %}">コメントを投稿する</a>
{% endif %}
</header>

{% if subject.college is not None %}
<h3>専門科目</h3>
<p>{{ subject.college }}  |  {{ subject.school }}</p>
{% else %}
<h3>一般教養科目</h3>
{% endif %}
<p>科目:{{ subject.name }}</p>
<p>担当教官:{{ subject.professor }}</p>
<div class="comment">
<p>コメント</p>
{% if comments.count != 0 %}
    {% for comment in comments %}
        <p>{{ comment.user.username }}さんのコメント  {{ comment.created_at }}</p>
        <p>{{ comment.text }}</p>
        {{ comment.like.num }}いいね
        {% if request.user.is_authenticated %}
                {% if  request.user not in comment.like.user.all %}
                    <form action="{% url 'app:push_like' subject_pk=subject.pk like_pk=comment.like.pk do='like' %}" method="post">{% csrf_token %}
                        <button type="submit" value="{{ comment.pk }}"><i class="fas fa-lg fa-heart like-red">いいねする</i></button>
                    </form>
                {% else %}
                    <form action="{% url 'app:push_like' subject_pk=subject.pk like_pk=comment.like.pk do='unlike' %}" method="post">{% csrf_token %}
                        <button type="submit" value="{{ comment.pk }}"><i class="fas fa-lg fa-heart">いいねをやめる</i></button>
                    </form>
                {% endif %}
        {% endif %}
        <br>
    {% endfor %}
{% else %}
    <p>まだコメントはありません。</p>
    {% if request.user.is_authenticated %}
    <p>{{ user.username }}さん、{{ subject.name　}}の講義についてご存知なら書き込んでみましょう！！</p>
{% endif %}

{% endif %}
</div>
{% endblock %}